default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

test: &test
  <<: *default
  database: pice-a-cake_test

cucumber:
  <<: *test

development: &default
  adapter: postgresql
  database: pice-a-cake_development
  encoding: unicode
  host: localhost
  min_messages: warning
  timeout: 5000
  username: postgres

production: &deploy
  encoding: unicode
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
